/* The following code was generated by JFlex 1.4.3 on 19/06/22 06:54 PM */

package AnalizadorL;
import static AnalizadorL.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 19/06/22 06:54 PM from the specification file
 * <tt>C:/Users/alexl/eclipse-workspace/Analizador/src/AnalizadorL/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\25\2\0\1\3\22\0\1\3\1\54\1\4\2\12"+
    "\1\7\1\11\1\5\1\21\1\22\1\24\1\20\1\7\1\13\1\15"+
    "\1\23\1\2\11\14\1\56\1\55\1\52\1\53\1\10\2\12\4\1"+
    "\1\17\25\1\1\6\1\0\1\6\1\12\1\1\1\12\1\37\1\50"+
    "\1\43\1\35\1\16\1\27\1\45\1\33\1\26\2\1\1\34\1\36"+
    "\1\40\1\30\1\44\1\1\1\31\1\41\1\42\1\47\1\46\1\32"+
    "\1\1\1\51\1\1\1\6\1\11\1\6\101\0\1\12\2\0\1\12"+
    "\uff3d\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\10\1\3\1\13\1\7\1\10"+
    "\1\14\16\2\1\11\1\15\1\12\1\16\1\17\1\3"+
    "\1\0\1\5\1\20\1\6\1\21\2\0\2\2\1\0"+
    "\1\4\1\0\1\13\27\2\1\22\1\23\1\24\1\0"+
    "\1\25\1\0\1\20\1\6\1\26\1\0\2\2\2\0"+
    "\22\2\1\0\1\27\4\2\1\3\1\4\7\2\1\25"+
    "\5\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\57"+
    "\0\57\0\u0149\0\57\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234"+
    "\0\57\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d"+
    "\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5"+
    "\0\u0524\0\u0553\0\57\0\57\0\u0582\0\u05b1\0\u05e0\0\353"+
    "\0\u060f\0\57\0\u063e\0\u0205\0\u066d\0\u069c\0\u06cb\0\u06fa"+
    "\0\u0729\0\136\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843"+
    "\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb"+
    "\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33"+
    "\0\u0b62\0\57\0\57\0\57\0\u0b91\0\u0b91\0\u0bc0\0\u0bef"+
    "\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67"+
    "\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf"+
    "\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057"+
    "\0\u1086\0\u10b5\0\u10e4\0\u1113\0\u1142\0\u1171\0\u11a0\0\57"+
    "\0\u0729\0\u11cf\0\u11fe\0\u122d\0\u125c\0\u128b\0\u12ba\0\u12e9"+
    "\0\u1318\0\u1347\0\u1376\0\u13a5\0\u13d4\0\u1403";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\2\1\14\1\15\1\2\1\16\1\3"+
    "\1\11\1\17\1\10\1\20\1\11\1\21\1\22\1\23"+
    "\1\3\1\24\1\25\2\3\1\26\1\27\1\3\1\30"+
    "\1\31\1\32\1\33\1\34\1\3\1\35\1\36\1\37"+
    "\1\3\1\40\1\41\1\42\1\43\1\44\60\0\2\3"+
    "\11\0\1\3\1\0\2\3\6\0\24\3\7\0\1\45"+
    "\11\0\1\45\1\46\44\0\1\5\54\0\3\47\1\50"+
    "\1\0\17\47\1\0\31\47\1\0\2\51\2\0\1\7"+
    "\6\0\1\51\1\0\2\51\6\0\24\51\60\0\1\52"+
    "\5\0\1\4\10\0\1\53\1\15\4\0\1\54\37\0"+
    "\1\15\11\0\1\15\1\46\42\0\2\3\11\0\1\3"+
    "\1\0\2\3\6\0\6\3\1\55\3\3\1\56\11\3"+
    "\20\0\1\57\66\0\1\60\1\61\33\0\2\3\11\0"+
    "\1\3\1\0\2\3\6\0\1\3\1\62\10\3\1\63"+
    "\11\3\6\0\2\3\11\0\1\3\1\0\2\3\6\0"+
    "\1\64\1\3\1\65\3\3\1\66\2\3\1\67\7\3"+
    "\1\70\2\3\6\0\2\3\11\0\1\3\1\0\1\71"+
    "\1\3\6\0\24\3\6\0\2\3\11\0\1\3\1\0"+
    "\2\3\6\0\3\3\1\72\1\3\1\73\16\3\6\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\2\3\1\62"+
    "\21\3\6\0\2\3\11\0\1\3\1\0\1\74\1\3"+
    "\6\0\11\3\1\75\12\3\6\0\2\3\11\0\1\3"+
    "\1\0\1\76\1\3\6\0\21\3\1\77\2\3\6\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\4\3\1\100"+
    "\7\3\1\101\7\3\6\0\2\3\11\0\1\3\1\0"+
    "\2\3\6\0\3\3\1\102\1\3\1\103\16\3\6\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\5\3\1\104"+
    "\3\3\1\105\12\3\6\0\2\3\11\0\1\3\1\0"+
    "\2\3\6\0\1\62\2\3\1\106\20\3\6\0\2\3"+
    "\11\0\1\3\1\0\2\3\6\0\2\3\1\107\21\3"+
    "\6\0\2\3\11\0\1\3\1\0\2\3\6\0\12\3"+
    "\1\110\11\3\6\0\2\3\11\0\1\3\1\0\2\3"+
    "\6\0\2\3\1\111\21\3\60\0\1\112\56\0\1\113"+
    "\56\0\1\114\5\0\1\45\11\0\1\45\44\0\1\115"+
    "\11\0\1\116\1\0\2\117\40\0\3\47\1\120\1\0"+
    "\17\47\1\0\31\47\1\0\2\121\2\0\1\122\6\0"+
    "\1\121\1\0\2\121\6\0\24\121\21\0\1\123\43\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\13\3\1\124"+
    "\10\3\6\0\2\3\11\0\1\3\1\0\2\3\6\0"+
    "\7\3\1\125\14\3\7\0\1\126\11\0\1\126\42\0"+
    "\25\60\1\0\31\60\1\0\23\61\1\127\32\61\1\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\14\3\1\62"+
    "\7\3\6\0\2\3\11\0\1\3\1\0\2\3\6\0"+
    "\12\3\1\130\11\3\6\0\2\3\11\0\1\3\1\0"+
    "\2\3\6\0\3\3\1\62\20\3\6\0\2\3\11\0"+
    "\1\3\1\0\2\3\6\0\2\3\1\131\21\3\6\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\6\3\1\55"+
    "\15\3\6\0\2\3\11\0\1\3\1\0\2\3\6\0"+
    "\12\3\1\132\11\3\6\0\2\3\11\0\1\3\1\0"+
    "\2\3\6\0\11\3\1\133\2\3\1\134\1\3\1\135"+
    "\5\3\6\0\2\3\11\0\1\3\1\0\2\3\6\0"+
    "\1\136\23\3\6\0\2\3\11\0\1\3\1\0\2\3"+
    "\6\0\1\137\23\3\6\0\2\3\11\0\1\3\1\0"+
    "\2\3\6\0\14\3\1\140\7\3\6\0\2\3\11\0"+
    "\1\3\1\0\2\3\6\0\1\141\23\3\6\0\2\3"+
    "\11\0\1\3\1\0\2\3\6\0\4\3\1\62\17\3"+
    "\6\0\2\3\11\0\1\3\1\0\2\3\6\0\6\3"+
    "\1\142\15\3\6\0\2\3\11\0\1\3\1\0\2\3"+
    "\6\0\1\143\23\3\6\0\2\3\11\0\1\3\1\0"+
    "\2\3\6\0\3\3\1\144\20\3\6\0\2\3\11\0"+
    "\1\3\1\0\2\3\6\0\21\3\1\124\1\3\1\62"+
    "\6\0\2\3\11\0\1\3\1\0\1\141\1\3\6\0"+
    "\1\145\23\3\6\0\2\3\11\0\1\3\1\0\2\3"+
    "\6\0\11\3\1\65\12\3\6\0\2\3\11\0\1\3"+
    "\1\0\2\3\6\0\13\3\1\124\1\146\7\3\6\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\2\3\1\147"+
    "\21\3\6\0\2\3\11\0\1\3\1\0\2\3\6\0"+
    "\1\133\23\3\6\0\2\3\11\0\1\3\1\0\2\3"+
    "\6\0\14\3\1\150\7\3\6\0\2\3\11\0\1\3"+
    "\1\0\2\3\6\0\2\3\1\151\21\3\7\0\1\115"+
    "\11\0\1\116\55\0\1\152\4\0\1\152\42\0\1\120"+
    "\53\0\2\121\2\0\1\153\6\0\1\121\1\0\2\121"+
    "\6\0\24\121\12\0\1\122\53\0\1\123\11\0\1\123"+
    "\1\46\42\0\2\3\11\0\1\3\1\0\1\62\1\3"+
    "\6\0\24\3\6\0\2\3\11\0\1\3\1\0\2\3"+
    "\6\0\1\154\1\62\2\3\1\155\3\3\1\62\2\3"+
    "\1\156\1\3\1\157\1\62\5\3\7\0\1\126\11\0"+
    "\1\126\5\0\1\160\35\0\22\61\1\161\1\127\32\61"+
    "\1\0\2\3\11\0\1\3\1\0\2\3\6\0\11\3"+
    "\1\142\12\3\6\0\2\3\11\0\1\3\1\0\2\3"+
    "\6\0\11\3\1\63\12\3\6\0\2\3\11\0\1\3"+
    "\1\0\2\3\6\0\14\3\1\162\7\3\6\0\2\3"+
    "\11\0\1\3\1\0\2\3\6\0\7\3\1\62\14\3"+
    "\6\0\2\3\11\0\1\3\1\0\2\3\6\0\21\3"+
    "\1\163\2\3\6\0\2\3\11\0\1\3\1\0\1\131"+
    "\1\3\6\0\24\3\6\0\2\3\11\0\1\3\1\0"+
    "\2\3\6\0\14\3\1\124\7\3\6\0\2\3\11\0"+
    "\1\3\1\0\2\3\6\0\6\3\1\124\15\3\6\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\5\3\1\164"+
    "\16\3\6\0\2\3\11\0\1\3\1\0\2\3\6\0"+
    "\12\3\1\62\11\3\6\0\2\3\11\0\1\3\1\0"+
    "\2\3\6\0\6\3\1\62\15\3\6\0\2\3\11\0"+
    "\1\3\1\0\2\3\6\0\14\3\1\146\7\3\6\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\1\165\23\3"+
    "\6\0\2\3\11\0\1\3\1\0\2\3\6\0\13\3"+
    "\1\62\10\3\6\0\2\3\11\0\1\3\1\0\2\3"+
    "\6\0\15\3\1\166\6\3\6\0\2\3\11\0\1\3"+
    "\1\0\2\3\6\0\17\3\1\167\4\3\6\0\2\3"+
    "\11\0\1\3\1\0\2\3\6\0\1\142\23\3\6\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\6\3\1\170"+
    "\15\3\21\0\1\171\47\0\1\153\52\0\2\3\11\0"+
    "\1\3\1\0\2\3\6\0\1\3\1\62\22\3\6\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\5\3\1\73"+
    "\16\3\6\0\2\3\11\0\1\3\1\0\2\3\6\0"+
    "\4\3\1\100\17\3\6\0\2\3\11\0\1\3\1\0"+
    "\2\3\6\0\11\3\1\55\12\3\6\0\2\3\11\0"+
    "\1\3\1\0\2\3\6\0\1\172\23\3\6\0\2\3"+
    "\11\0\1\3\1\0\2\3\6\0\3\3\1\141\20\3"+
    "\6\0\2\3\11\0\1\3\1\0\2\3\6\0\2\3"+
    "\1\133\21\3\6\0\2\3\11\0\1\3\1\0\2\3"+
    "\6\0\12\3\1\173\11\3\6\0\2\3\11\0\1\3"+
    "\1\0\2\3\6\0\5\3\1\62\16\3\6\0\2\3"+
    "\11\0\1\3\1\0\2\3\6\0\3\3\1\174\20\3"+
    "\6\0\2\3\11\0\1\3\1\0\1\175\1\3\6\0"+
    "\24\3\7\0\1\171\11\0\1\171\43\0\2\3\11\0"+
    "\1\3\1\0\2\3\6\0\2\3\1\141\21\3\6\0"+
    "\2\3\11\0\1\3\1\0\2\3\6\0\17\3\1\62"+
    "\4\3\6\0\2\3\11\0\1\3\1\0\2\3\6\0"+
    "\11\3\1\176\12\3\6\0\2\3\11\0\1\3\1\0"+
    "\2\3\6\0\11\3\1\141\12\3\6\0\2\3\11\0"+
    "\1\3\1\0\2\3\6\0\10\3\1\62\13\3\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5170];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\2\11\1\1\1\11\5\1\1\11"+
    "\21\1\2\11\1\1\1\0\3\1\1\11\2\0\2\1"+
    "\1\0\1\1\1\0\30\1\3\11\1\0\1\1\1\0"+
    "\3\1\1\0\2\1\2\0\22\1\1\0\5\1\1\11"+
    "\16\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 142) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 18: 
          { lexeme=yytext(); return meniq;
          }
        case 24: break;
        case 11: 
          { lexeme=yytext(); return reservada;
          }
        case 25: break;
        case 10: 
          { lexeme=yytext(); return logico;
          }
        case 26: break;
        case 8: 
          { lexeme=yytext(); return aritmetico;
          }
        case 27: break;
        case 5: 
          { return ERRcad;
          }
        case 28: break;
        case 14: 
          { lexeme=yytext();return finSentencia;
          }
        case 29: break;
        case 17: 
          { lexeme=yytext(); return mayiq;
          }
        case 30: break;
        case 15: 
          { lexeme=yytext();return puntos;
          }
        case 31: break;
        case 23: 
          { return ERRMDig;
          }
        case 32: break;
        case 3: 
          { lexeme=yytext(); return nume;
          }
        case 33: break;
        case 22: 
          { lexeme=yytext(); return litcar;
          }
        case 34: break;
        case 12: 
          { lexeme=yytext(); return salto;
          }
        case 35: break;
        case 2: 
          { lexeme=yytext(); return id;
          }
        case 36: break;
        case 7: 
          { lexeme=yytext(); return agrupacion;
          }
        case 37: break;
        case 16: 
          { lexeme=yytext(); return litcad;
          }
        case 38: break;
        case 6: 
          { return ERRchar;
          }
        case 39: break;
        case 9: 
          { lexeme=yytext(); return relacional;
          }
        case 40: break;
        case 21: 
          { lexeme=yytext(); return numf;
          }
        case 41: break;
        case 19: 
          { lexeme=yytext(); return igual;
          }
        case 42: break;
        case 13: 
          { lexeme=yytext(); return asignacion;
          }
        case 43: break;
        case 20: 
          { lexeme=yytext(); return dif;
          }
        case 44: break;
        case 1: 
          { return ERROR;
          }
        case 45: break;
        case 4: 
          { /*Ignore*/
          }
        case 46: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
